language: ruby
rvm:
    - 1.9.3
    - 2.0.0
    - 2.2.1

gemfile:
    - Gemfile
    - gemfiles/activesupport3.2.x.gemfile
    - gemfiles/activesupport4.2.x-ams0.9.x.gemfile

script: time './script/travis.sh'

branches:
    only: master
