language: ruby
rvm:
    - 1.8.7
    - 1.9.2
    - 1.9.3
    - 2.0.0

gemfile:
    - Gemfile
    - gemfiles/activesupport3.2.x.gemfile

matrix:
    exclude:
        -   rvm: 1.8.7
            gemfile: Gemfile
        -   rvm: 1.9.2
            gemfile: Gemfile

script: time './script/travis.sh'

branches:
    only: master
